In [47]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.pyplot as plt

In [48]:
df = pd.read_csv(r"C:\Users\Repair\Downloads\mall_sales 2023-2025.csv")
df.head()

,Customer Name,State,Product,Units Sold,Unit Price,Total Sale,Sale Date,Sales Channel,Order ID
0,NaN,rivers,KEYBOARD,NaN,NaN,NaN,27-04-2025,Online,NaN
1,Allison Hill,Lagos,Headphones,NaN,267992.94,NaN,15-03-2024,Wholesale,4c636e95-025f-4543-8997-623ae0723d96
2,Noah Rhodes,Anambra,Keyboard,NaN,42364.41,NaN,10-12-2024,NaN,edaf3766-1b78-4ede-9a4f-fc0c9165f2ed
3,Angie Henderson,Delta,Keyboard,NaN,279444.94,NaN,05-04-2024,NaN,74503887-48d9-4846-95c5-51fcfba57cc8
4,Daniel Wagner,Delta,Tablet,NaN,95899.74,NaN,12-01-2025,NaN,8639bd41-8b15-4d94-a42d-0cd7fd359f6a

In [49]:
 df.describe()

       Units Sold     Unit Price    Total Sale
count  155.000000     495.000000  1.370000e+02
mean    46.858065  155703.699212  7.075166e+06
std     26.973156   84443.013217  6.338224e+06
min      1.000000    1403.130000  5.788704e+04
25%     24.500000   84873.975000  1.788402e+06
50%     47.000000  157889.240000  5.049848e+06
75%     67.500000  224577.170000  1.119981e+07
max    100.000000  299437.800000  2.873459e+07

In [50]:
df.isnull().sum()

Customer Name     43
State              0
Product            0
Units Sold       395
Unit Price        55
Total Sale       413
Sale Date          0
Sales Channel    106
Order ID          40
dtype: int64

In [73]:
mean_value = df['Unit Price'].mean()
df['Unit Price'] = df['Unit Price'].fillna(mean_value).round().astype('int64')

In [52]:
df.head()

,Customer Name,State,Product,Units Sold,Unit Price,Total Sale,Sale Date,Sales Channel,Order ID
0,NaN,rivers,KEYBOARD,NaN,155703.699212,NaN,27-04-2025,Online,NaN
1,Allison Hill,Lagos,Headphones,NaN,267992.940000,NaN,15-03-2024,Wholesale,4c636e95-025f-4543-8997-623ae0723d96
2,Noah Rhodes,Anambra,Keyboard,NaN,42364.410000,NaN,10-12-2024,NaN,edaf3766-1b78-4ede-9a4f-fc0c9165f2ed
3,Angie Henderson,Delta,Keyboard,NaN,279444.940000,NaN,05-04-2024,NaN,74503887-48d9-4846-95c5-51fcfba57cc8
4,Daniel Wagner,Delta,Tablet,NaN,95899.740000,NaN,12-01-2025,NaN,8639bd41-8b15-4d94-a42d-0cd7fd359f6a

In [71]:
mean_value = df['Units Sold'].mean()
df['Units Sold'] = df['Units Sold'].fillna(mean_value).round().astype('int64')

In [74]:
df.head(15)

,Customer Name,State,Product,Units Sold,Unit Price,Total Sale,Sale Date,Sales Channel,Order ID
0,NaN,rivers,KEYBOARD,47,155704,7295974,27-04-2025,Online,NaN
1,Allison Hill,Lagos,Headphones,47,267993,12557630,15-03-2024,Wholesale,4c636e95-025f-4543-8997-623ae0723d96
2,Noah Rhodes,Anambra,Keyboard,47,42364,1985114,10-12-2024,Wholesale,edaf3766-1b78-4ede-9a4f-fc0c9165f2ed
3,Angie Henderson,Delta,Keyboard,47,279445,13094249,05-04-2024,Wholesale,74503887-48d9-4846-95c5-51fcfba57cc8
4,Daniel Wagner,Delta,Tablet,47,95900,4493676,12-01-2025,Wholesale,8639bd41-8b15-4d94-a42d-0cd7fd359f6a
5,Cristian Santos,Oyo,Camera,47,118190,5538150,30-08-2023,Direct,225aed6c-f045-4043-a3a6-8a707e710b55
6,Connie Lawrence,Rivers,Tablet,36,185142,6665108,10-09-2024,Wholesale,45d8a6ad-77d0-459e-8114-14f8d9df0d0e
7,Abigail Shaffer,Imo,Keyboard,47,252859,11848496,04-09-2024,Online,54a7b69b-1cd6-4b09-8f0e-6d2b315c167a
8,Gina Moore,Kano,CAMERA,47,178321,8355755,21-02-2024,Wholesale,a5f60735-757b-4b29-bb2a-a1462999394c
9,Gabrielle Davis,plateau,Tablet,47,152441,7143083,02-06-2025,Direct,039b058c-2faa-4e0b-b7f6-0cdf41dc1c60
10,Ryan Munoz,Niger,Keyboard,47,155704,7295974,28-02-2024,Direct,4b86b5a1-ca6f-4ff8-964c-fbd2bc92fd81
11,Monica Herrera,Abuja,Laptop,3,153159,459478,02-05-2025,Retail,317304b5-c1dd-484a-aca5-8d95915a1c30
12,Jamie Arnold,Lagos,Tablet,43,147209,6329990,10-11-2023,Wholesale,a383889a-db2c-4ac8-9c67-83932ced3c0d
13,Jamie Arnold,Kano,Camera,47,169096,7923503,13-01-2025,Wholesale,6d7df5d0-d3b5-4af7-a7ce-378fe5a4983b
14,Lisa Hensley,Enugu,Tablet,27,142730,3853719,12-01-2025,Direct,NaN

In [56]:
df['Customer Name'] = df['Customer Name'].ffill()
df['Sales Channel'] = df['Sales Channel'].ffill()

In [75]:
df.head(15)

,Customer Name,State,Product,Units Sold,Unit Price,Total Sale,Sale Date,Sales Channel,Order ID
0,NaN,rivers,KEYBOARD,47,155704,7295974,27-04-2025,Online,NaN
1,Allison Hill,Lagos,Headphones,47,267993,12557630,15-03-2024,Wholesale,4c636e95-025f-4543-8997-623ae0723d96
2,Noah Rhodes,Anambra,Keyboard,47,42364,1985114,10-12-2024,Wholesale,edaf3766-1b78-4ede-9a4f-fc0c9165f2ed
3,Angie Henderson,Delta,Keyboard,47,279445,13094249,05-04-2024,Wholesale,74503887-48d9-4846-95c5-51fcfba57cc8
4,Daniel Wagner,Delta,Tablet,47,95900,4493676,12-01-2025,Wholesale,8639bd41-8b15-4d94-a42d-0cd7fd359f6a
5,Cristian Santos,Oyo,Camera,47,118190,5538150,30-08-2023,Direct,225aed6c-f045-4043-a3a6-8a707e710b55
6,Connie Lawrence,Rivers,Tablet,36,185142,6665108,10-09-2024,Wholesale,45d8a6ad-77d0-459e-8114-14f8d9df0d0e
7,Abigail Shaffer,Imo,Keyboard,47,252859,11848496,04-09-2024,Online,54a7b69b-1cd6-4b09-8f0e-6d2b315c167a
8,Gina Moore,Kano,CAMERA,47,178321,8355755,21-02-2024,Wholesale,a5f60735-757b-4b29-bb2a-a1462999394c
9,Gabrielle Davis,plateau,Tablet,47,152441,7143083,02-06-2025,Direct,039b058c-2faa-4e0b-b7f6-0cdf41dc1c60
10,Ryan Munoz,Niger,Keyboard,47,155704,7295974,28-02-2024,Direct,4b86b5a1-ca6f-4ff8-964c-fbd2bc92fd81
11,Monica Herrera,Abuja,Laptop,3,153159,459478,02-05-2025,Retail,317304b5-c1dd-484a-aca5-8d95915a1c30
12,Jamie Arnold,Lagos,Tablet,43,147209,6329990,10-11-2023,Wholesale,a383889a-db2c-4ac8-9c67-83932ced3c0d
13,Jamie Arnold,Kano,Camera,47,169096,7923503,13-01-2025,Wholesale,6d7df5d0-d3b5-4af7-a7ce-378fe5a4983b
14,Lisa Hensley,Enugu,Tablet,27,142730,3853719,12-01-2025,Direct,NaN

In [65]:
import duckdb

# Write your query pointing directly to the 'df' variable
sql_query = """
SELECT 
    "Product",
    "Unit Price",
    "Units Sold",
    ("Unit Price" * "Units Sold") AS "Total Sale"
FROM 
    df;
"""

# Run the query using DuckDB's direct connection execution
result_df = duckdb.query(sql_query).df()
result_df.head()

      Product     Unit Price  Units Sold    Total Sale
0    KEYBOARD  155703.699212   46.858065  7.295974e+06
1  Headphones  267992.940000   46.858065  1.255763e+07
2    Keyboard   42364.410000   46.858065  1.985114e+06
3    Keyboard  279444.940000   46.858065  1.309425e+07
4      Tablet   95899.740000   46.858065  4.493676e+06

In [76]:
df['Total Sale'] = (df['Unit Price'] * df['Units Sold']).round().astype('int64')

# Check the results to make sure the NaNs are gone
df.head(15)

,Customer Name,State,Product,Units Sold,Unit Price,Total Sale,Sale Date,Sales Channel,Order ID
0,NaN,rivers,KEYBOARD,47,155704,7318088,27-04-2025,Online,NaN
1,Allison Hill,Lagos,Headphones,47,267993,12595671,15-03-2024,Wholesale,4c636e95-025f-4543-8997-623ae0723d96
2,Noah Rhodes,Anambra,Keyboard,47,42364,1991108,10-12-2024,Wholesale,edaf3766-1b78-4ede-9a4f-fc0c9165f2ed
3,Angie Henderson,Delta,Keyboard,47,279445,13133915,05-04-2024,Wholesale,74503887-48d9-4846-95c5-51fcfba57cc8
4,Daniel Wagner,Delta,Tablet,47,95900,4507300,12-01-2025,Wholesale,8639bd41-8b15-4d94-a42d-0cd7fd359f6a
5,Cristian Santos,Oyo,Camera,47,118190,5554930,30-08-2023,Direct,225aed6c-f045-4043-a3a6-8a707e710b55
6,Connie Lawrence,Rivers,Tablet,36,185142,6665112,10-09-2024,Wholesale,45d8a6ad-77d0-459e-8114-14f8d9df0d0e
7,Abigail Shaffer,Imo,Keyboard,47,252859,11884373,04-09-2024,Online,54a7b69b-1cd6-4b09-8f0e-6d2b315c167a
8,Gina Moore,Kano,CAMERA,47,178321,8381087,21-02-2024,Wholesale,a5f60735-757b-4b29-bb2a-a1462999394c
9,Gabrielle Davis,plateau,Tablet,47,152441,7164727,02-06-2025,Direct,039b058c-2faa-4e0b-b7f6-0cdf41dc1c60
10,Ryan Munoz,Niger,Keyboard,47,155704,7318088,28-02-2024,Direct,4b86b5a1-ca6f-4ff8-964c-fbd2bc92fd81
11,Monica Herrera,Abuja,Laptop,3,153159,459477,02-05-2025,Retail,317304b5-c1dd-484a-aca5-8d95915a1c30
12,Jamie Arnold,Lagos,Tablet,43,147209,6329987,10-11-2023,Wholesale,a383889a-db2c-4ac8-9c67-83932ced3c0d
13,Jamie Arnold,Kano,Camera,47,169096,7947512,13-01-2025,Wholesale,6d7df5d0-d3b5-4af7-a7ce-378fe5a4983b
14,Lisa Hensley,Enugu,Tablet,27,142730,3853710,12-01-2025,Direct,NaN

In [77]:
df['Customer Name'] = df['Customer Name'].bfill()

In [79]:
df.head(10)

,Customer Name,State,Product,Units Sold,Unit Price,Total Sale,Sale Date,Sales Channel,Order ID
0,Allison Hill,rivers,KEYBOARD,47,155704,7318088,27-04-2025,Online,NaN
1,Allison Hill,Lagos,Headphones,47,267993,12595671,15-03-2024,Wholesale,4c636e95-025f-4543-8997-623ae0723d96
2,Noah Rhodes,Anambra,Keyboard,47,42364,1991108,10-12-2024,Wholesale,edaf3766-1b78-4ede-9a4f-fc0c9165f2ed
3,Angie Henderson,Delta,Keyboard,47,279445,13133915,05-04-2024,Wholesale,74503887-48d9-4846-95c5-51fcfba57cc8
4,Daniel Wagner,Delta,Tablet,47,95900,4507300,12-01-2025,Wholesale,8639bd41-8b15-4d94-a42d-0cd7fd359f6a
5,Cristian Santos,Oyo,Camera,47,118190,5554930,30-08-2023,Direct,225aed6c-f045-4043-a3a6-8a707e710b55
6,Connie Lawrence,Rivers,Tablet,36,185142,6665112,10-09-2024,Wholesale,45d8a6ad-77d0-459e-8114-14f8d9df0d0e
7,Abigail Shaffer,Imo,Keyboard,47,252859,11884373,04-09-2024,Online,54a7b69b-1cd6-4b09-8f0e-6d2b315c167a
8,Gina Moore,Kano,CAMERA,47,178321,8381087,21-02-2024,Wholesale,a5f60735-757b-4b29-bb2a-a1462999394c
9,Gabrielle Davis,plateau,Tablet,47,152441,7164727,02-06-2025,Direct,039b058c-2faa-4e0b-b7f6-0cdf41dc1c60

In [80]:
df.isnull().sum()

Customer Name     0
State             0
Product           0
Units Sold        0
Unit Price        0
Total Sale        0
Sale Date         0
Sales Channel     0
Order ID         40
dtype: int64

In [86]:
df['Product'] = df['Product'].str.lower()

# Check the changes
df.head()

,Customer Name,State,Product,Units Sold,Unit Price,Total Sale,Sale Date,Sales Channel,Order ID,Year
0,Allison Hill,rivers,keyboard,47,155704,7318088,2025-04-27,Online,NaN,2025
1,Allison Hill,Lagos,headphones,47,267993,12595671,2024-03-15,Wholesale,4c636e95-025f-4543-8997-623ae0723d96,2024
2,Noah Rhodes,Anambra,keyboard,47,42364,1991108,2024-12-10,Wholesale,edaf3766-1b78-4ede-9a4f-fc0c9165f2ed,2024
3,Angie Henderson,Delta,keyboard,47,279445,13133915,2024-04-05,Wholesale,74503887-48d9-4846-95c5-51fcfba57cc8,2024
4,Daniel Wagner,Delta,tablet,47,95900,4507300,2025-01-12,Wholesale,8639bd41-8b15-4d94-a42d-0cd7fd359f6a,2025

In [81]:
state_counts = df['State'].value_counts()

print(state_counts)

State
Delta          34
Imo            34
Anambra        30
Kano           30
Niger          29
Rivers         28
Enugu          28
Abuja          25
Sokoto         25
Bauchi         24
Ekiti          24
Katsina        23
Benue          23
Plateau        21
Kaduna         21
Borno          21
Oyo            19
Osun           19
Lagos          16
Cross River    14
lagos           7
oyo             6
delta           5
imo             4
abuja           4
rivers          3
plateau         3
kano            3
enugu           3
kaduna          3
cross river     3
ekiti           3
anambra         2
katsina         2
osun            2
niger           2
borno           2
bauchi          2
benue           2
sokoto          1
Name: count, dtype: int64

In [88]:
state_sales = df.groupby('State')['Total Sale'].sum().reset_index()
state_sales = state_sales.sort_values(by='Total Sale', ascending=False)
state_sales

          State  Total Sale
11         Kano   266784859
9           Imo   254270603
6         Delta   251858857
12      Katsina   199403203
18       Rivers   199190667
14        Niger   198745728
8         Enugu   192044829
1       Anambra   190692532
19       Sokoto   186253687
3         Benue   184078355
15         Osun   180722232
10       Kaduna   180224092
16          Oyo   165605033
7         Ekiti   165182181
0         Abuja   162609358
2        Bauchi   161305315
17      Plateau   125360958
13        Lagos   114472654
5   Cross River    98892576
4         Borno    92241490
33        lagos    56876463
36          oyo    42866444
26        delta    38188985
30       kaduna    30737906
38       rivers    30717408
28        enugu    27894218
22       bauchi    27064856
25  cross river    26253277
37      plateau    25079289
29          imo    23158688
24        borno    22061089
27        ekiti    21153102
21      anambra    16893915
39       sokoto    15620094
34        niger    12880842
20        abuja    12824907
32      katsina    10925838
23        benue     8774968
31         kano     7625763
35         osun     6942035

In [83]:
df['Sale Date'] = pd.to_datetime(df['Sale Date'], format='%d-%m-%Y')
df['Year'] = df['Sale Date'].dt.year

yearly_sales = df.groupby('Year')['Total Sale'].sum().reset_index()
yearly_sales = yearly_sales.sort_values(by='Year')
yearly_sales

   Year  Total Sale
0  2023   806848930
1  2024  2204152823
2  2025  1023477543

In [94]:
customer_sales = df[df['Customer Name'].notnull()].groupby('Customer Name')['Total Sale'].sum().reset_index()
customer_sales = customer_sales.sort_values(by='Total Sale', ascending=False)
top_10_customers = customer_sales.head(10)
top_10_customers

         Customer Name  Total Sale
210  Jeanette Harrison    28734580
28        Angela Lopez    26075154
185     Heather Bolton    24677726
451     Sierra Johnson    22421104
436    Shane Henderson    22228462
27          Angela Lin    21985548
362     Michelle Brown    21793746
242        John Daniel    21774395
341      Matthew Moore    21391251
500      William Jones    21024322

In [107]:
# 1. Filter out missing names, group by Customer Name, and sum the Total Sale numbers
customer_revenue = df[df['Customer Name'].notnull()].groupby('Customer Name')['Total Sale'].sum().reset_index()

# 2. Sort the customers from the highest spender to the lowest
customer_revenue = customer_revenue.sort_values(by='Total Sale', ascending=False)

# Display the full summary table
customer_revenue

         Customer Name  Total Sale
210  Jeanette Harrison    28734580
28        Angela Lopez    26075154
185     Heather Bolton    24677726
451     Sierra Johnson    22421104
436    Shane Henderson    22228462
..                 ...         ...
122     Darlene Miller      119662
3         Adam Burgess       85728
278     Kathryn Snyder       65941
428     Sandra Aguilar       62816
216      Jeffrey Mills       57888

[506 rows x 2 columns]

In [93]:

product_sales = df.groupby('Product')['Total Sale'].sum().reset_index()

product_sales = product_sales.sort_values(by='Total Sale', ascending=False)

top_10_products = product_sales.head(10)

top_10_products

      Product  Total Sale
3    keyboard   735430764
7      tablet   635826231
6       phone   508491608
5     monitor   490479083
4      laptop   443302460
2  headphones   434932467
1     charger   401477948
0      camera   384538735

In [100]:
# 1. Group by State and add up the Units Sold
state_units = df.groupby('State')['Units Sold'].sum().reset_index()

# 2. Sort from the highest units sold to the lowest
state_units = state_units.sort_values(by='Units Sold', ascending=False)

# Display the summary table
state_units

          State  Units Sold
6         Delta        1608
9           Imo        1602
11         Kano        1561
1       Anambra        1390
14        Niger        1381
18       Rivers        1289
8         Enugu        1235
19       Sokoto        1172
10       Kaduna        1138
2        Bauchi        1130
3         Benue        1102
0         Abuja        1067
7         Ekiti        1053
12      Katsina        1049
16          Oyo         999
17      Plateau         981
15         Osun         954
4         Borno         817
13        Lagos         717
5   Cross River         702
33        lagos         347
36          oyo         282
26        delta         253
29          imo         195
37      plateau         174
25  cross river         152
38       rivers         147
30       kaduna         145
20        abuja         144
27        ekiti         141
28        enugu         141
24        borno         130
31         kano         112
23        benue          98
22       bauchi          94
21      anambra          94
35         osun          64
32      katsina          59
34        niger          55
39       sokoto          54

In [101]:
# 1. Group by State and Product, then calculate the average Unit Price
state_product_pricing = df.groupby(['State', 'Product'])['Unit Price'].mean().reset_index()

# 2. Rename the column to reflect that it is an average
state_product_pricing.columns = ['State', 'Product', 'Avg Unit Price']

# 3. Sort alphabetically by State and then by highest price down
state_product_pricing = state_product_pricing.sort_values(by=['State', 'Avg Unit Price'], ascending=[True, False])

# Display the summary table
state_product_pricing

       State   Product  Avg Unit Price
5      Abuja     phone       252604.60
4      Abuja   monitor       155236.75
2      Abuja  keyboard       149089.60
6      Abuja    tablet       125834.50
3      Abuja    laptop       114102.00
..       ...       ...             ...
201  plateau    tablet       152441.00
200  plateau  keyboard        69284.00
202   rivers   charger       298048.00
203   rivers  keyboard       155704.00
204   sokoto  keyboard       289261.00

[205 rows x 3 columns]

In [103]:
# 1. Group by Sales Channel and calculate the sum for both columns
channel_summary = df.groupby('Sales Channel').agg(
    Total_Sales=('Total Sale', 'sum'),
    Total_Units_Sold=('Units Sold', 'sum')
).reset_index()

# 2. Sort from highest revenue-generating channel to lowest
channel_summary = channel_summary.sort_values(by='Total_Sales', ascending=False)

# Display the combined table
channel_summary

  Sales Channel  Total_Sales  Total_Units_Sold
0        Direct   1091587060              7077
2        Retail   1060455333              6612
3     Wholesale    951605065              6239
1        Online    930831838              5900

In [112]:
# 1. Extract the Year and Month periods (creates a clean format like '2024-01', '2024-02')
df['Month_Year'] = df['Sale Date'].dt.to_period('M')

# 2. Group by the new Month_Year period and sum the Total Sale numbers
monthly_sales = df.groupby('Month_Year')['Total Sale'].sum().reset_index()

# 3. Sort chronologically from oldest month to newest month
monthly_sales = monthly_sales.sort_values(by='Month_Year')

# 4. Convert Month_Year back to a string format so it plays nice with charts and Excel
monthly_sales['Month_Year'] = monthly_sales['Month_Year'].astype(str)

# Display the summary table
monthly_sales

   Month_Year  Total Sale
0     2023-07    59594738
1     2023-08   174572734
2     2023-09    87368344
3     2023-10   215245063
4     2023-11   149321710
5     2023-12   120746341
6     2024-01   149350832
7     2024-02   168930355
8     2024-03   247090242
9     2024-04   173255708
10    2024-05   198739845
11    2024-06    82408714
12    2024-07   253438872
13    2024-08   195715951
14    2024-09   217136226
15    2024-10   197311614
16    2024-11   145391504
17    2024-12   175382960
18    2025-01   191491384
19    2025-02   157308418
20    2025-03   157220552
21    2025-04   165977716
22    2025-05   137125262
23    2025-06   129354096
24    2025-07    85000115

In [113]:
# 1. Group by Product and count how many rows (transactions) exist for each name
product_counts = df.groupby('Product').size().reset_index(name='Total Transactions')

# 2. Sort from the most frequently bought product down to the least
product_counts = product_counts.sort_values(by='Total Transactions', ascending=False)

# Display the summary leaderboard
product_counts

      Product  Total Transactions
3    keyboard                  89
7      tablet                  85
5     monitor                  71
4      laptop                  67
0      camera                  65
1     charger                  59
2  headphones                  57
6       phone                  57

In [105]:
df.head(15)

,Customer Name,State,Product,Units Sold,Unit Price,Total Sale,Sale Date,Sales Channel,Order ID,Year
0,Allison Hill,rivers,keyboard,47,155704,7318088,2025-04-27,Online,NaN,2025
1,Allison Hill,Lagos,headphones,47,267993,12595671,2024-03-15,Wholesale,4c636e95-025f-4543-8997-623ae0723d96,2024
2,Noah Rhodes,Anambra,keyboard,47,42364,1991108,2024-12-10,Wholesale,edaf3766-1b78-4ede-9a4f-fc0c9165f2ed,2024
3,Angie Henderson,Delta,keyboard,47,279445,13133915,2024-04-05,Wholesale,74503887-48d9-4846-95c5-51fcfba57cc8,2024
4,Daniel Wagner,Delta,tablet,47,95900,4507300,2025-01-12,Wholesale,8639bd41-8b15-4d94-a42d-0cd7fd359f6a,2025
5,Cristian Santos,Oyo,camera,47,118190,5554930,2023-08-30,Direct,225aed6c-f045-4043-a3a6-8a707e710b55,2023
6,Connie Lawrence,Rivers,tablet,36,185142,6665112,2024-09-10,Wholesale,45d8a6ad-77d0-459e-8114-14f8d9df0d0e,2024
7,Abigail Shaffer,Imo,keyboard,47,252859,11884373,2024-09-04,Online,54a7b69b-1cd6-4b09-8f0e-6d2b315c167a,2024
8,Gina Moore,Kano,camera,47,178321,8381087,2024-02-21,Wholesale,a5f60735-757b-4b29-bb2a-a1462999394c,2024
9,Gabrielle Davis,plateau,tablet,47,152441,7164727,2025-06-02,Direct,039b058c-2faa-4e0b-b7f6-0cdf41dc1c60,2025
10,Ryan Munoz,Niger,keyboard,47,155704,7318088,2024-02-28,Direct,4b86b5a1-ca6f-4ff8-964c-fbd2bc92fd81,2024
11,Monica Herrera,Abuja,laptop,3,153159,459477,2025-05-02,Retail,317304b5-c1dd-484a-aca5-8d95915a1c30,2025
12,Jamie Arnold,Lagos,tablet,43,147209,6329987,2023-11-10,Wholesale,a383889a-db2c-4ac8-9c67-83932ced3c0d,2023
13,Jamie Arnold,Kano,camera,47,169096,7947512,2025-01-13,Wholesale,6d7df5d0-d3b5-4af7-a7ce-378fe5a4983b,2025
14,Lisa Hensley,Enugu,tablet,27,142730,3853710,2025-01-12,Direct,NaN,2025

In [111]:
import os

In [130]:
import os
import pandas as pd


# 1. Setup your secure target folder path
save_path = r"C:\Users\Repair\Desktop\mall sales"
os.makedirs(save_path, exist_ok=True)
excel_file = os.path.join(save_path, "final_sales_report.xlsx")

# 2. Make sure Sale Date is datetime format before running aggregations
df['Sale Date'] = pd.to_datetime(df['Sale Date'], format='%d-%m-%Y', errors='coerce')

# 3. Compile all your analytical reporting dataframes
monthly_sales         = df.groupby(df['Sale Date'].dt.to_period('M'))['Total Sale'].sum().reset_index()
channel_summary       = df.groupby('Sales Channel').agg(Total_Sales=('Total Sale', 'sum'), Total_Units_Sold=('Units Sold', 'sum')).reset_index()
state_product_pricing = df.groupby(['State', 'Product'])['Unit Price'].mean().reset_index()
state_units           = df.groupby('State')['Units Sold'].sum().reset_index()
top_10_products       = df.groupby('Product')['Total Sale'].sum().reset_index().sort_values(by='Total Sale', ascending=False).head(10)
customer_revenue      = df.groupby('Customer Name')['Total Sale'].sum().reset_index().sort_values(by='Total Sale', ascending=False)
top_10_customers      = customer_revenue.head(10)

# Format time period to string for clean Excel integration
monthly_sales['Sale Date'] = monthly_sales['Sale Date'].astype(str)

# 4. Save the entire workspace to Excel across organized spreadsheet tabs
with pd.ExcelWriter(excel_file, engine='openpyxl') as writer:
    # SAVES YOUR MAIN CLEAN DATA TABLE FROM THE SCREENSHOT
    df.to_excel(writer, sheet_name="master_clean_data", index=False)
    
    # SAVES ALL YOUR METRIC INSIGHTS
    monthly_sales.to_excel(writer, sheet_name="monthly_sales", index=False)
    channel_summary.to_excel(writer, sheet_name="channel_summary", index=False)
    state_product_pricing.to_excel(writer, sheet_name="state_product_pricing", index=False)
    state_units.to_excel(writer, sheet_name="state_units", index=False)
    top_10_products.to_excel(writer, sheet_name="top_10_products", index=False)
    customer_revenue.to_excel(writer, sheet_name="customer_revenue", index=False)
    top_10_customers.to_excel(writer, sheet_name="top_10_customers", index=False)

print("🎉 Complete success! Your master clean dataset and all 7 metrics are safely saved to your desktop!")

🎉 Complete success! Your master clean dataset and all 7 metrics are safely saved to your desktop!